spring.application.name=shipment-tracking-service
server.port=8080

# SQLEXPRESS Ba\u011Flant\u0131 URL'si
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=LogiTrackDB;encrypt=true;trustServerCertificate=true;
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:senin_mevcut_sifren}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Hibernate Ayarlar\u0131
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true